//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NKL_2210900035_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUAN_TRI
    {
        public int ma_quan_tri { get; set; }
        public string mat_khau { get; set; }
        public string ten_dang_nhap { get; set; }
        public string email { get; set; }
        public System.DateTime ngay_tao { get; set; }
        public byte trang_thai { get; set; }
    }
}
