//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT3_NKL_2210900035_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STORY()
        {
            this.CHAPTERs = new HashSet<CHAPTER>();
            this.COMMENTs = new HashSet<COMMENT>();
        }
    
        public int ma_truyen { get; set; }
        public string ten_truyen { get; set; }
        public string tac_gia { get; set; }
        public string the_loai { get; set; }
        public string mo_ta { get; set; }
        public System.DateTime ngay_dang { get; set; }
        public int nguoi_dang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAPTER> CHAPTERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
    }
}
